"""remove_unique_constraint_from_homepage_content_section

Revision ID: 3903148d3268
Revises: fbf13420a46c
Create Date: 2025-09-17 02:04:15.926963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3903148d3268'
down_revision = 'fbf13420a46c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepage_content_section'), table_name='homepage_content')
    op.create_index(op.f('ix_homepage_content_section'), 'homepage_content', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepage_content_section'), table_name='homepage_content')
    op.create_index(op.f('ix_homepage_content_section'), 'homepage_content', ['section'], unique=True)
    # ### end Alembic commands ###

